items:
- uid: com.microsoft.azure.management.graphrbac._graph_error_exception
  id: _graph_error_exception
  parent: com.microsoft.azure.management.graphrbac
  children:
  - com.microsoft.azure.management.graphrbac._graph_error_exception.getBody()
  - com.microsoft.azure.management.graphrbac._graph_error_exception.getResponse()
  - com.microsoft.azure.management.graphrbac._graph_error_exception.GraphErrorException()
  - com.microsoft.azure.management.graphrbac._graph_error_exception.GraphErrorException(final String)
  - com.microsoft.azure.management.graphrbac._graph_error_exception.GraphErrorException(final String,final Throwable)
  - com.microsoft.azure.management.graphrbac._graph_error_exception.GraphErrorException(final Throwable)
  - com.microsoft.azure.management.graphrbac._graph_error_exception.setBody(GraphError)
  - com.microsoft.azure.management.graphrbac._graph_error_exception.setResponse(Response)
  href: com.microsoft.azure.management.graphrbac._graph_error_exception.yml
  langs:
  - java
  name: GraphErrorException
  fullName: com.microsoft.azure.management.graphrbac.GraphErrorException
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-graph-rbac/src/main/java/com/microsoft/azure/management/graphrbac/GraphErrorException.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-graph-rbac/src/main/java/com/microsoft/azure/management/graphrbac/GraphErrorException.java
    startLine: 16
  package: com.microsoft.azure.management.graphrbac
  summary: <p>Exception thrown for an invalid response with <xref href="com.microsoft.azure.management.graphrbac._graph_error" data-throw-if-not-resolved="false"></xref> information. </p>
  syntax: &o1
    content: public class GraphErrorException
  inheritance:
  - java.lang.Object
  - RestException
- uid: com.microsoft.azure.management.graphrbac._graph_error_exception.getBody()
  id: getBody()
  parent: com.microsoft.azure.management.graphrbac._graph_error_exception
  href: com.microsoft.azure.management.graphrbac._graph_error_exception.yml
  langs:
  - java
  name: getBody()
  fullName: GraphError com.microsoft.azure.management.graphrbac.GraphErrorException.getBody()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-graph-rbac/src/main/java/com/microsoft/azure/management/graphrbac/GraphErrorException.java
    startLine: 67
  package: com.microsoft.azure.management.graphrbac
  summary: >-
    <p>Gets the HTTP response body.</p>

    <p></p>
  syntax:
    content: public GraphError getBody()
    return:
      type: com.microsoft.azure.management.graphrbac._graph_error
      description: <p>the response body </p>
- uid: com.microsoft.azure.management.graphrbac._graph_error_exception.getResponse()
  id: getResponse()
  parent: com.microsoft.azure.management.graphrbac._graph_error_exception
  href: com.microsoft.azure.management.graphrbac._graph_error_exception.yml
  langs:
  - java
  name: getResponse()
  fullName: Response com.microsoft.azure.management.graphrbac.GraphErrorException.getResponse()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-graph-rbac/src/main/java/com/microsoft/azure/management/graphrbac/GraphErrorException.java
    startLine: 59
  package: com.microsoft.azure.management.graphrbac
  summary: >-
    <p>Gets information about the associated HTTP response.</p>

    <p></p>
  syntax:
    content: public Response getResponse()
    return:
      type: e9d34ed6
      description: <p>the HTTP response </p>
- uid: com.microsoft.azure.management.graphrbac._graph_error_exception.GraphErrorException()
  id: GraphErrorException()
  parent: com.microsoft.azure.management.graphrbac._graph_error_exception
  href: com.microsoft.azure.management.graphrbac._graph_error_exception.yml
  langs:
  - java
  name: GraphErrorException()
  fullName: com.microsoft.azure.management.graphrbac.GraphErrorException.GraphErrorException()
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-graph-rbac/src/main/java/com/microsoft/azure/management/graphrbac/GraphErrorException.java
    startLine: 28
  package: com.microsoft.azure.management.graphrbac
  summary: <p>Initializes a new instance of the <xref href="com.microsoft.azure.management.graphrbac._graph_error_exception" data-throw-if-not-resolved="false"></xref> class. </p>
  syntax:
    content: public GraphErrorException()
- uid: com.microsoft.azure.management.graphrbac._graph_error_exception.GraphErrorException(final String)
  id: GraphErrorException(final String)
  parent: com.microsoft.azure.management.graphrbac._graph_error_exception
  href: com.microsoft.azure.management.graphrbac._graph_error_exception.yml
  langs:
  - java
  name: GraphErrorException(final String message)
  fullName: com.microsoft.azure.management.graphrbac.GraphErrorException.GraphErrorException(final String message)
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-graph-rbac/src/main/java/com/microsoft/azure/management/graphrbac/GraphErrorException.java
    startLine: 34
  package: com.microsoft.azure.management.graphrbac
  summary: >-
    <p>Initializes a new instance of the <xref href="com.microsoft.azure.management.graphrbac._graph_error_exception" data-throw-if-not-resolved="false"></xref> class.</p>

    <p></p>
  syntax:
    content: public GraphErrorException(final String message)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>The exception message. </p>
- uid: com.microsoft.azure.management.graphrbac._graph_error_exception.GraphErrorException(final String,final Throwable)
  id: GraphErrorException(final String,final Throwable)
  parent: com.microsoft.azure.management.graphrbac._graph_error_exception
  href: com.microsoft.azure.management.graphrbac._graph_error_exception.yml
  langs:
  - java
  name: GraphErrorException(final String message, final Throwable cause)
  fullName: com.microsoft.azure.management.graphrbac.GraphErrorException.GraphErrorException(final String message, final Throwable cause)
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-graph-rbac/src/main/java/com/microsoft/azure/management/graphrbac/GraphErrorException.java
    startLine: 43
  package: com.microsoft.azure.management.graphrbac
  summary: >-
    <p>Initializes a new instance of the <xref href="com.microsoft.azure.management.graphrbac._graph_error_exception" data-throw-if-not-resolved="false"></xref> class.</p>

    <p></p>
  syntax:
    content: public GraphErrorException(final String message, final Throwable cause)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>the exception message </p>
    - id: cause
      type: fa00b19f
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.azure.management.graphrbac._graph_error_exception.GraphErrorException(final Throwable)
  id: GraphErrorException(final Throwable)
  parent: com.microsoft.azure.management.graphrbac._graph_error_exception
  href: com.microsoft.azure.management.graphrbac._graph_error_exception.yml
  langs:
  - java
  name: GraphErrorException(final Throwable cause)
  fullName: com.microsoft.azure.management.graphrbac.GraphErrorException.GraphErrorException(final Throwable cause)
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-graph-rbac/src/main/java/com/microsoft/azure/management/graphrbac/GraphErrorException.java
    startLine: 51
  package: com.microsoft.azure.management.graphrbac
  summary: >-
    <p>Initializes a new instance of the <xref href="com.microsoft.azure.management.graphrbac._graph_error_exception" data-throw-if-not-resolved="false"></xref> class.</p>

    <p></p>
  syntax:
    content: public GraphErrorException(final Throwable cause)
    parameters:
    - id: cause
      type: fa00b19f
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.azure.management.graphrbac._graph_error_exception.setBody(GraphError)
  id: setBody(GraphError)
  parent: com.microsoft.azure.management.graphrbac._graph_error_exception
  href: com.microsoft.azure.management.graphrbac._graph_error_exception.yml
  langs:
  - java
  name: setBody(GraphError body)
  fullName: void com.microsoft.azure.management.graphrbac.GraphErrorException.setBody(GraphError body)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-graph-rbac/src/main/java/com/microsoft/azure/management/graphrbac/GraphErrorException.java
    startLine: 83
  package: com.microsoft.azure.management.graphrbac
  summary: >-
    <p>Sets the HTTP response body.</p>

    <p></p>
  syntax:
    content: public void setBody(GraphError body)
    parameters:
    - id: body
      type: com.microsoft.azure.management.graphrbac._graph_error
      description: <p>the response body </p>
- uid: com.microsoft.azure.management.graphrbac._graph_error_exception.setResponse(Response)
  id: setResponse(Response)
  parent: com.microsoft.azure.management.graphrbac._graph_error_exception
  href: com.microsoft.azure.management.graphrbac._graph_error_exception.yml
  langs:
  - java
  name: setResponse(Response response)
  fullName: void com.microsoft.azure.management.graphrbac.GraphErrorException.setResponse(Response response)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-graph-rbac/src/main/java/com/microsoft/azure/management/graphrbac/GraphErrorException.java
    startLine: 75
  package: com.microsoft.azure.management.graphrbac
  summary: >-
    <p>Sets the HTTP response.</p>

    <p></p>
  syntax:
    content: public void setResponse(Response response)
    parameters:
    - id: response
      type: e9d34ed6
      description: <p>the HTTP response </p>
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: fa00b19f
  spec.java:
  - name: final Throwable
    fullName: final Throwable
- uid: e9d34ed6
  spec.java:
  - name: Response
    fullName: Response
- uid: com.microsoft.azure.management.graphrbac._graph_error
  parent: com.microsoft.azure.management.graphrbac
  href: com.microsoft.azure.management.graphrbac._graph_error.yml
  name: GraphError
  fullName: com.microsoft.azure.management.graphrbac.GraphError
  type: Class
  summary: <p>Active Directory error information. </p>
  syntax:
    content: public class GraphError
- uid: com.microsoft.azure.management.graphrbac._graph_error_exception
  parent: com.microsoft.azure.management.graphrbac
  href: com.microsoft.azure.management.graphrbac._graph_error_exception.yml
  name: GraphErrorException
  fullName: com.microsoft.azure.management.graphrbac.GraphErrorException
  type: Class
  summary: <p>Exception thrown for an invalid response with <xref href="com.microsoft.azure.management.graphrbac._graph_error" data-throw-if-not-resolved="false"></xref> information. </p>
  syntax: *o1
